### ISSUE TITLE
CASS Homepage Link

### ISSUE THREAD

**Issue by kelnera** [osu-cass/cass-pelican#29] opened 2016-07-22 21:20 UTC
@Kennric @ramereth @osu-cass/cass-media On the menu bar on the right side of any page, when you click the CASS logo (not the link that actually says "Center for Applied Systems and Software") it redirects to the OSL website, not the CASS homepage.

**Comment by leian7** [comment] 2016-08-03 16:27
Duplicate of #39

**Closed by leian7** 2016-08-03 16:27 UTC
